#!/bin/sh
set -e
update-rc.d openstatus-server defaults
if id www-data > /dev/null 2>&1; then
  chown -R www-data:www-data /etc/openstatus
  chown -R www-data:www-data /usr/share/openstatus-server/*
fi

service openstatus-server restart
